### ISSUE TITLE
Can't login with UDM

### ISSUE THREAD

**Issue by hakarune** [tomwpublic/hubitat_unifiEvents#5]
Was working fine with self hosted, but moved to UDM Pro and can't connect

**Comment by tomwpublic** [comment]
I just tried it with my UniFi OS device (a Cloud Key Gen2 Plus) and I could log in correctly.  A couple of thoughts:

What do the State Variables look like for your UniFi Controller virtual device, especially the 'UniFiOS' value?  You may need to hit Configure or Initialize again to get those set correctly if you re-used the previous virtual device from your self-hosted controller.

Are you sure that the account and login credentials that you used in the Hubitat virtual device are valid for your new UDM configuration?

**Comment by tomwpublic** [comment]
@hakarune FYI

**Comment by hakarune** [comment]
> I just tried it with my UniFi OS device (a Cloud Key Gen2 Plus) and I could log in correctly. A couple of thoughts:
> 
> What do the State Variables look like for your UniFi Controller virtual device, especially the 'UniFiOS' value? You may need to hit Configure or Initialize again to get those set correctly if you re-used the previous virtual device from your self-hosted controller.
> 
> Are you sure that the account and login credentials that you used in the Hubitat virtual device are valid for your new UDM configuration?

Going to be honest I have no clue what happened to this thing. Last night I created the local user account to go with this controller on hubitat and entered in the IP 10.1.1.1 and it wouldn't work, pressed initialize probably 10 times as well. Created a second user, still didn't work. Tried playing with the url/ip adding the /extensions even and nothing. Today I read your response and go in, it's still not working. I edit the ip back to just 10.1.1.1 and nothing and then press edit device ID (didn't change the ID or anything) and pressed save and now it's online. All the children are back online...

**Comment by tomwpublic** [comment]
That's weird, but I'm glad it's working now.
